name: Add Release Notes from Pull Request Commits
description: Creates Release Notes from the commits of a Pull Request, and adds them to the body of the pull request. 
inputs:
  pull_number:
    description: The number of the PR to generate notes for. You only need to specify this if you're calling from an event other than pull_request
    required: true
    default: ${{ github.event.pull_request.number }}
# outputs:
  # notes:
    # description: The generated release notes, as added to the PR body
runs:
  using: node16
  main: notes.js
